[package]
name = "live_at_ardan_Rust"
version = "0.1.0"
edition = "2021"

[dependencies]


[workspace]
members =[ "session1/authentication",
    "session1/hello-world"
    , "session1/login", "session1/variables"]
